name: newsapi
description: Use the NewsApi v2 service in Dart. The library has a clear return structure and an easy-to-use API.
version: 2.0.0
homepage: https://github.com/YeungKC/NewsApi

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0-prev3
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^3.3.1
  equatable: ^2.0.0
  json_annotation: ^4.0.1

dev_dependencies:
  retrofit_generator: ^4.2.0
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  test: ^1.16.8
  pedantic: ^1.11.0
